// <auto-generated />
namespace MyGym.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021821190_Second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
